const express = require('express');
require('dotenv').config();
const DBconnection = require('./config/db');
const authRoutes = require('./routes/auth.routes');
const userRoutes = require('./routes/user.routes');
const adminRoutes = require('./routes/admin.routes');
const eventRoutes = require('./routes/event.routes');
const participantRoutes = require('./routes/participant.routes');
const { createAdmin } = require('./utils/admin-creation');
const app = express();
const port = process.env.PORT || 3000;
app.use(express.json());
DBconnection();
app.use('/api/auth', authRoutes);
app.use('/api/home', userRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/events', eventRoutes);
app.use('/api/participants', participantRoutes);
app.listen(port, () => {
    console.log(`Listening on port ${port}`);
    createAdmin();
});
